
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.1+9a89d02ff for .NET Framework
      Сборка начата 19.03.2024 15:13:50.
      Проект "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.53
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/3.27.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.1+9a89d02ff for .NET Framework
      Сборка начата 19.03.2024 15:13:50.
      Проект "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.41
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/3.27.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-tn9xvx"
      binary: "C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-tn9xvx"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-tn9xvx'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_9dde3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.4.1+9a89d02ff for .NET Framework
        Сборка начата 19.03.2024 15:13:51.
        Проект "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-tn9xvx\\cmTC_9dde3.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_9dde3.dir\\Debug\\".
          Создание каталога "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-tn9xvx\\Debug\\".
          Создание каталога "cmTC_9dde3.dir\\Debug\\cmTC_9dde3.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_9dde3.dir\\Debug\\cmTC_9dde3.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9dde3.dir\\Debug\\\\" /Fd"cmTC_9dde3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.34.31937 для x64
          CMakeCCompilerABI.c
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9dde3.dir\\Debug\\\\" /Fd"cmTC_9dde3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-tn9xvx\\Debug\\cmTC_9dde3.exe" /INCREMENTAL /ILK:"cmTC_9dde3.dir\\Debug\\cmTC_9dde3.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-tn9xvx/Debug/cmTC_9dde3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-tn9xvx/Debug/cmTC_9dde3.lib" /MACHINE:X64  /machine:x64 cmTC_9dde3.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_9dde3.vcxproj -> C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-tn9xvx\\Debug\\cmTC_9dde3.exe
        FinalizeBuildStatus:
          Файл "cmTC_9dde3.dir\\Debug\\cmTC_9dde3.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_9dde3.dir\\Debug\\cmTC_9dde3.tlog\\cmTC_9dde3.lastbuildstate".
        Сборка проекта "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-tn9xvx\\cmTC_9dde3.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.39
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-etoq6h"
      binary: "C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-etoq6h"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-etoq6h'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_dbab6.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.4.1+9a89d02ff for .NET Framework
        Сборка начата 19.03.2024 15:13:51.
        Проект "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-etoq6h\\cmTC_dbab6.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_dbab6.dir\\Debug\\".
          Создание каталога "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-etoq6h\\Debug\\".
          Создание каталога "cmTC_dbab6.dir\\Debug\\cmTC_dbab6.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_dbab6.dir\\Debug\\cmTC_dbab6.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_dbab6.dir\\Debug\\\\" /Fd"cmTC_dbab6.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.34.31937 для x64
          CMakeCXXCompilerABI.cpp
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_dbab6.dir\\Debug\\\\" /Fd"cmTC_dbab6.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-etoq6h\\Debug\\cmTC_dbab6.exe" /INCREMENTAL /ILK:"cmTC_dbab6.dir\\Debug\\cmTC_dbab6.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-etoq6h/Debug/cmTC_dbab6.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/betterty/source/repos/DrWeb/DrWeb/build/CMakeFiles/CMakeScratch/TryCompile-etoq6h/Debug/cmTC_dbab6.lib" /MACHINE:X64  /machine:x64 cmTC_dbab6.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_dbab6.vcxproj -> C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-etoq6h\\Debug\\cmTC_dbab6.exe
        FinalizeBuildStatus:
          Файл "cmTC_dbab6.dir\\Debug\\cmTC_dbab6.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_dbab6.dir\\Debug\\cmTC_dbab6.tlog\\cmTC_dbab6.lastbuildstate".
        Сборка проекта "C:\\Users\\betterty\\source\\repos\\DrWeb\\DrWeb\\build\\CMakeFiles\\CMakeScratch\\TryCompile-etoq6h\\cmTC_dbab6.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.40
        
      exitCode: 0
...
